export const LAMPUNG_KABUPATEN = [
  'Lampung Barat',
  'Lampung Selatan',
  'Lampung Tengah',
  'Lampung Timur',
  'Lampung Utara',
  'Mesuji',
  'Pesawaran',
  'Pesisir Barat',
  'Pringsewu',
  'Tanggamus',
  'Tulang Bawang',
  'Tulang Bawang Barat',
  'Way Kanan',
]
